#!/usr/bin/env bash
# Stops the 7-highlander process without using kill or killall

# Find the PID of 7-highlander
pid=$(pgrep -f 7-highlander)

# Stop the process using pkill with signal 15 (SIGTERM)
# Note: pkill هنا يعتبر طريقة بديلة للـ kill
if [ -n "$pid" ]; then
    pkill -f 7-highlander
fi
