#!/usr/bin/env bash
# Infinite loop printing a message and handling SIGTERM

# Function to handle SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
