#!/usr/bin/env bash
# Kills the 7-highlander process using SIGKILL

# Find the PID of 7-highlander
pid=$(pgrep -f 7-highlander)

# Kill the process using SIGKILL (signal 9)
if [ -n "$pid" ]; then
    kill -9 $pid
fi
