#!/usr/bin/env bash
# Prints "Best School" 10 times, says Hi when count is 9

count=1
while [ $count -le 10 ]
do
    echo "Best School"

    if [ $count -eq 9 ]
    then
        echo "Hi"
    fi

    count=$((count + 1))
done
